apiVersion: apps/v1
kind: Deployment
metadata:
  name: vam-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vam-frontend
  template:
    metadata:
      labels:
        app: vam-frontend
    spec:
      containers:
        - name: vam-frontend
          image: vam-frontend:1.0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vam-frontend-service
spec:
  type: NodePort
  selector:
    app: vam-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
